import {
  ClockCircleFilled,
  CommentOutlined,
  CalendarOutlined,
  CheckOutlined,
  DashboardOutlined,
  EnvironmentOutlined,
  LeftOutlined,
  LogoutOutlined,
  ProfileOutlined,
  KeyOutlined,
  RightOutlined,
  SettingOutlined,
  StockOutlined,
  TeamOutlined,
  UserOutlined,
  WechatOutlined,
} from '@ant-design/icons';

export {
  ClockCircleFilled,
  CommentOutlined,
  CalendarOutlined,
  CheckOutlined,
  DashboardOutlined,
  EnvironmentOutlined,
  LeftOutlined,
  LogoutOutlined,
  ProfileOutlined,
  KeyOutlined,
  RightOutlined,
  SettingOutlined,
  StockOutlined,
  TeamOutlined,
  UserOutlined,
  WechatOutlined,
};
